name: SmartwayCaoc-PullRequest

on:
  workflow_dispatch:
  pull_request:

jobs:
  smartway-caoc:
    uses: ./.github/workflows/smartway-caoc-build.yml
    with:
      lib-version: 1.0.${{ github.event.pull_request.number }}.${{ github.run_number }}
      configuration: Release
    secrets: inherit

