name: SmartwayCaoc-Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  smartway-caoc:
    uses: ./.github/workflows/smartway-caoc-publish.yml
    with:
      lib-version: ${{github.ref_name}}
      configuration: Release
    secrets: inherit

  notify:
    if: ${{ success() }}
    needs: [smartway-caoc]
    uses: ./.github/workflows/notify.yml
    secrets: inherit
