name: SmartwayCaoc-Build

on:
  workflow_call:
    inputs:
      lib-version:
        required: true
        type: string
      configuration:
        required: true
        type: string

jobs:
  build-smartway-caoc:
    name: Build lib
    runs-on: [self-hosted, xamarin-android]
    steps:
    - name: Clean Workspace
      uses: mickem/clean-after-action@v2

    - name: Checkout
      uses: actions/checkout@v4

    - name: Modify AssemblyInfo files
      uses: mingjun97/file-regex-replace@v1
      with:
        regex: 'AssemblyVersion\("(.*?)"\)'
        replacement: 'AssemblyVersion("${{ inputs.lib-version }}")'
        include: 'AssemblyInfo.cs'

    - name: Restore packages
      run: nuget restore Cat.Ereza.Customactivityoncrash.sln

    - name: Build the lib
      run: msbuild Cat.Ereza.Customactivityoncrash.sln -p:Configuration=${{ inputs.configuration }} -clp:Summary

    - name: Send Slack Notification
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "[${{ github.workflow }}/${{ github.job }} : ${{ github.event.number || github.ref_name }}] ${{ job.status }}",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Pipeline ${{ github.workflow }} launched by ${{ github.actor }} ${{ job.status }} on ${{ runner.name }}"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Pipeline on Github",
                    "emoji": true
                  },
                  "value": "Github",
                  "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{github.run_id }}",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
